apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: docker.io/andrewin25/nestjs-server:latest
          ports:
            - containerPort: 4000
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/nest_campaigns"